### ISSUE TITLE
REI Compat Broken

### ISSUE THREAD

**Issue by Diamondman121314** [robotbrain/luminiferous-uplands#34]
The REI plugin does not work with REI 3.0+.

https://gist.github.com/Diamondman121314/75c100eeb447ebb0f70f00c2e9b41ad4#file-gistfile1-txt-L1436

**Comment by devvoid** [comment]
Sorry it took so long to get back to you on this; I can't reproduce this at all. Please try the following:

- Use the newest version of both Uplands and REI.
- Disable all mods except Uplands, REI, and the Fabric API.

If neither of those work, let me know and I'll see if there's anything I can do.

**Comment by Khitiara** [comment]
This was supposed to be closed, I fixed it some time ago lol
